# Generated by Django 4.0.1 on 2022-02-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('by', models.CharField(default='NAME', max_length=50, verbose_name='by')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('by', models.CharField(default='NAME', max_length=50, verbose_name='by')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('by', models.CharField(default='NAME', max_length=50, verbose_name='by')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
