# Generated by Django 4.0.1 on 2022-02-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('by', models.CharField(default='NAME_NEW', max_length=50, verbose_name='by')),
                ('descendants', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kids', models.TextField(default='kids', max_length=250)),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('_type', models.TextField(default='TYPE', max_length=250)),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('by', models.CharField(default='NAME_SHOW', max_length=50, verbose_name='by')),
                ('descendants', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kids', models.TextField(default='kids', max_length=250)),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(default='text', max_length=250)),
                ('time', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('_type', models.TextField(default='TYPE', max_length=250)),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.RemoveField(
            model_name='job',
            name='text',
        ),
        migrations.AddField(
            model_name='ask',
            name='_type',
            field=models.TextField(default='TYPE', max_length=250),
        ),
        migrations.AddField(
            model_name='ask',
            name='descendants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ask',
            name='kids',
            field=models.TextField(default='kids', max_length=250),
        ),
        migrations.AddField(
            model_name='ask',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ask',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='_type',
            field=models.TextField(default='TYPE', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='ask',
            name='by',
            field=models.CharField(default='NAME_ASK', max_length=50, verbose_name='by'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.TextField(default='text', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='by',
            field=models.CharField(default='NAME_JOB', max_length=50, verbose_name='by'),
        ),
    ]
