# Generated by Django 4.0.1 on 2022-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_new_show_delete_story_remove_job_text_ask__type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
