# Generated by Django 4.0.1 on 2022-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ask__type_alter_ask_by_alter_ask_descendants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='kids',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='_type',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='_type',
            field=models.TextField(default='TYPE', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='kids',
            field=models.TextField(default='kids', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='_type',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='kids',
            field=models.TextField(default='kids', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='text',
            field=models.TextField(default='text', max_length=250, null=True),
        ),
    ]
