# Generated by Django 4.0.1 on 2022-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ask_kids_alter_ask_text_alter_job__type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
