# Generated by Django 4.0.1 on 2022-02-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_ask_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='text',
            field=models.TextField(default='text', null=True),
        ),
    ]
