# Generated by Django 4.0.1 on 2022-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_show_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='descendants',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
