# Generated by Django 4.0.1 on 2022-02-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_new_descendants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
