# Generated by Django 4.0.1 on 2022-02-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter product instance status', max_length=20, null=True, verbose_name='Product Instance Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
                ('status', models.ForeignKey(help_text='Change the state of an instance', on_delete=django.db.models.deletion.CASCADE, to='product_catalog.status', verbose_name='Product Instance Status')),
            ],
        ),
    ]
